# Generated by Django 3.0.4 on 2020-04-18 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('studio', models.CharField(max_length=300)),
                ('awards', models.CharField(blank=True, max_length=400)),
                ('joined_on', models.DateTimeField(null=True)),
                ('contacts', models.IntegerField(default=1)),
                ('email', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('hit1', models.CharField(blank=True, max_length=50)),
                ('hit2', models.CharField(blank=True, max_length=50)),
                ('hit3', models.CharField(blank=True, max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Share')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
