# Generated by Django 3.0.4 on 2020-04-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freestuff',
            name='type_choice',
            field=models.CharField(choices=[('Beat', 'Beat'), ('Violin Piece', 'Violin Piece'), ('Guitar Piece', 'Guitar Piece'), ('Piano piece', 'Piano piece'), ('Vocal piece', 'Vocal piece'), ('African piece', 'African piece'), ('Trumpet Piece', 'Trumpet Piece'), ('Saxaphone Piec', 'Saxaphone Piece')], max_length=20),
        ),
        migrations.AlterField(
            model_name='internationalmusic',
            name='type_choice',
            field=models.CharField(choices=[('Beat', 'Beat'), ('Violin Piece', 'Violin Piece'), ('Guitar Piece', 'Guitar Piece'), ('Piano piece', 'Piano piece'), ('Vocal piece', 'Vocal piece'), ('African piece', 'African piece'), ('Trumpet Piece', 'Trumpet Piece'), ('Saxaphone Piec', 'Saxaphone Piece')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='category_choice',
            field=models.CharField(blank=True, choices=[('Rnb', 'Rnb'), ('Pop', 'Pop'), ('Danncehall', 'Danncehall'), ('Afrobeat', 'Afrobeat'), ('Regae', 'Regae'), ('Afropop', 'Afropop')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='type_choice',
            field=models.CharField(blank=True, choices=[('Beat', 'Beat'), ('Violin Piece', 'Violin Piece'), ('Guitar Piece', 'Guitar Piece'), ('Piano piece', 'Piano piece'), ('Vocal piece', 'Vocal piece'), ('African piece', 'African piece'), ('Trumpet Piece', 'Trumpet Piece'), ('Saxaphone Piec', 'Saxaphone Piece')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ugandanmusic',
            name='type_choice',
            field=models.CharField(choices=[('Beat', 'Beat'), ('Violin Piece', 'Violin Piece'), ('Guitar Piece', 'Guitar Piece'), ('Piano piece', 'Piano piece'), ('Vocal piece', 'Vocal piece'), ('African piece', 'African piece'), ('Trumpet Piece', 'Trumpet Piece'), ('Saxaphone Piec', 'Saxaphone Piece')], max_length=20),
        ),
    ]
